export class Post {

  constructor() {}
  Id: number;
  statementDate = '';
  divorceDate = '';
  priorStatement = '';
  birthdate = '';
  otherBirthDate = '';
  marriageDate = '';
  separationDate = '';
  agreementExist = false;
   causeAction = '';
   custody = '';
   parentingTime = '';
   alimony = '';
   childSupport = '';
   equitableDistribution = '';
   counselFees = '';
   college = '';
   other = '';
   yourName = '';
   streetAddress = '';
   city = '';
   state = '';
   secondParty = '';
   secondAddress = '';
   secondCity = '';
   secondState = '';
   childOne = '';
   addressOne = '';
   birthOne = '';
   personOne = '';
   childTwo = '';
   addressTwo = '';
   birthTwo = '';
   personTwo = '';
   employerName = '';
   employerAddress = '';
   employerNameTwo = '';
   employerTwoAddress = '';
  insurance = false;
  type = false;
  medical = false;
  dental = false;
  prescription = false;
  life = false;
  disability = false;
  otherB = '';
  insuranceAvailable = false;
  sheet = false;
}
